# Generated by Django 5.0.6 on 2024-06-26 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_sellerprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerProfile',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profile'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
