# Generated by Django 5.0.6 on 2024-06-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_birth_year_profile_firstname_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_year',
        ),
    ]
