# Generated by Django 5.0.6 on 2024-06-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0006_remove_laptop_announce_year_remove_laptop_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartphoneBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'smartphone_brand',
                'db_table': 'smartphone_brand',
            },
        ),
        migrations.CreateModel(
            name='SmartphoneMainCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'smartphone_main_camera',
                'db_table': 'smartphone_main_camera',
            },
        ),
        migrations.CreateModel(
            name='SmartphoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'smartphone_model',
                'db_table': 'smartphone_model',
            },
        ),
        migrations.CreateModel(
            name='SmartphoneOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'smartphone_os',
                'db_table': 'smartphone_os',
            },
        ),
        migrations.CreateModel(
            name='SmartphoneSelfieCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'smartphone_selfie_camera',
                'db_table': 'smartphone_selfie_camera',
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('announce_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.year')),
                ('category', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ram')),
                ('storage_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.storage')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.smartphonebrand')),
                ('main_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.smartphonemaincamera')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.smartphonemodel')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.smartphoneos')),
                ('celfie_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.smartphoneselfiecamera')),
            ],
            options={
                'verbose_name_plural': 'smartphone',
                'db_table': 'smartphone',
            },
        ),
    ]
