# Generated by Django 5.0.6 on 2024-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product-pictures/default.jpg', null=True, upload_to='product-pictures'),
        ),
    ]
