# Generated by Django 5.0.6 on 2024-06-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_ram_smartphonebrand_smartphonemaincamera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'laptop_brand',
                'db_table': 'laptop_brand',
            },
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'laptop_model',
                'db_table': 'laptop_model',
            },
        ),
        migrations.CreateModel(
            name='LaptopOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'laptop_OS',
                'db_table': 'laptop_OS',
            },
        ),
        migrations.CreateModel(
            name='LaptopScreenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'laptop_screen_size',
                'db_table': 'laptop_screen_size',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('announce_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.year')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ram')),
                ('storage_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.storage')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.laptopbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.laptopmodel')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.laptopos')),
            ],
        ),
    ]
