# Generated by Django 5.0.6 on 2024-06-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_laptopbrand_laptopmodel_laptopos_laptopscreensize_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name_plural': 'laptop'},
        ),
        migrations.RemoveField(
            model_name='smartphonemodel',
            name='brand',
        ),
        migrations.AlterModelTable(
            name='laptop',
            table='laptop',
        ),
    ]
