# Generated by Django 5.0.6 on 2024-06-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_laptop_options_remove_smartphonemodel_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='announce_year',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='model',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage_capacity',
        ),
        migrations.DeleteModel(
            name='LaptopScreenSize',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='announce_year',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='celfie_camera',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='main_camera',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='model',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='storage_capacity',
        ),
        migrations.DeleteModel(
            name='LaptopBrand',
        ),
        migrations.DeleteModel(
            name='LaptopModel',
        ),
        migrations.DeleteModel(
            name='LaptopOS',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='SmartphoneBrand',
        ),
        migrations.DeleteModel(
            name='SmartphoneSelfieCamera',
        ),
        migrations.DeleteModel(
            name='SmartphoneMainCamera',
        ),
        migrations.DeleteModel(
            name='SmartphoneModel',
        ),
        migrations.DeleteModel(
            name='SmartphoneOS',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
