# Generated by Django 5.0.6 on 2024-06-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0006_remove_laptop_announce_year_remove_laptop_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cooling',
                'db_table': 'cooling',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CPU',
                'db_table': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'GPU',
                'db_table': 'GPU',
            },
        ),
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'laptop_brand',
                'db_table': 'laptop_brand',
            },
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'laptop_model',
                'db_table': 'laptop_model',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'OS',
                'db_table': 'OS',
            },
        ),
        migrations.CreateModel(
            name='PCType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'PC_type',
                'db_table': 'PC_type',
            },
        ),
        migrations.CreateModel(
            name='ScreenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'screen_size',
                'db_table': 'screen_size',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('cooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.cooling')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.gpu')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.os')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ram')),
                ('storage_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.storage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.pctype')),
                ('screen_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.screensize')),
            ],
            options={
                'verbose_name_plural': 'PC',
                'db_table': 'PC',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('announce_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.year')),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.gpu')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ram')),
                ('storage_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.storage')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.laptopbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.laptopmodel')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.os')),
                ('screen_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.screensize')),
            ],
            options={
                'verbose_name_plural': 'laptop',
                'db_table': 'laptop',
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('announce_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.year')),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.os')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ram')),
                ('screen_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.screensize')),
                ('storage_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.storage')),
            ],
            options={
                'verbose_name_plural': 'tablet',
                'db_table': 'tablet',
            },
        ),
    ]
