# Generated by Django 5.0.6 on 2024-06-14 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_alter_pc_category_alter_tablet_category_parts'),
        ('mainapp', '0006_remove_laptop_announce_year_remove_laptop_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='PartsOrAccessories',
        ),
        migrations.AlterModelOptions(
            name='partsoraccessories',
            options={'verbose_name_plural': 'parts_or_accessories'},
        ),
        migrations.AlterModelTable(
            name='partsoraccessories',
            table='parts_or_accessories',
        ),
    ]
