# Generated by Django 5.0.6 on 2024-06-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_rename_parts_partsoraccessories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsoraccessories',
            old_name='category',
            new_name='subcategory',
        ),
    ]
